# Generated by Django 4.0 on 2024-08-01 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institute_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='QualifyingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcourses', to='frontend.course')),
                ('prerequisite_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_subcourses', to='frontend.assessment')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prerequisite_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_topics', to='frontend.assignment')),
                ('subcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='frontend.subcourse')),
            ],
            options={
                'ordering': ['subcourse', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessments_completed', models.ManyToManyField(blank=True, related_name='user_progress_assessments', to='frontend.Assessment')),
                ('assignments_completed', models.ManyToManyField(blank=True, related_name='user_progress_assignments', to='frontend.Assignment')),
                ('courses', models.ManyToManyField(blank=True, related_name='user_progress_course', to='frontend.Course')),
                ('institutes', models.ManyToManyField(blank=True, related_name='user_progress_institute', to='frontend.Institute')),
                ('qualifying_tests_completed', models.ManyToManyField(blank=True, related_name='user_progress_tests', to='frontend.QualifyingTest')),
                ('subcourses', models.ManyToManyField(blank=True, related_name='user_progress_subcourse', to='frontend.SubCourse')),
                ('topics', models.ManyToManyField(blank=True, related_name='user_progress_topic', to='frontend.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='TestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('from_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_required', to='frontend.course')),
                ('to_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_prerequisite', to='frontend.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.course')),
                ('members', models.ManyToManyField(related_name='course_rooms', to='frontend.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institutes',
            field=models.ManyToManyField(related_name='courses', to='frontend.Institute'),
        ),
        migrations.AddField(
            model_name='course',
            name='qualifying_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='frontend.qualifyingtest'),
        ),
    ]
